"""Baked world landmass bitmap.

Rasterized from Natural Earth 110m land polygons (public domain) into a
360x160 equirectangular bit grid spanning latitude 84..-60. Regenerate
with a scanline pass over ne_110m_land.json if the projection ever changes.
"""

from __future__ import annotations

import base64
from functools import lru_cache

WIDTH = 360
HEIGHT = 160
LAT_TOP = 84.0
LAT_BOTTOM = -60.0

_BITMAP_B64 = (
    "AAAAAAAAAAAAAAAAAAAAAAAH/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACf//+AAf///4AAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD////H//////w+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AA+///8////////8AAAAAAAAAAYAAAAAAHwAAAAAAAAAAAAAAAAAAAAAAAAAAB////x////////AAAAA3/8AAAAAAAAAAP8A"
    "AAAAAAAAAAAAAAAAAAAAAAAAPAP7/wH///////+AAAAB/8AAAAAAAAAAAD9wAAAAAAAAAAAAAAAAAAAAAAAIA/gH/z//////"
    "//+AAAAA/nAAAAAAAAAAAAHgAAAAAAAAAAAAAAAAAAAAAA8AAAAP+AP////////AAAAAPAAAAAAAAAAAAAB8AAAAAAAAAAAA"
    "AAAAAAAAAHzHA+fGeAP///////8AAAAAAAAAAAAAP4AAAAP/+AAAAAAAAAAAAAAAAAAAAAP/4e3/8AAAf/////+AAAAAAAAA"
    "AAAH4AAAB////AAAB/oAAAAAAAAAAAAAAAA4AAB/4AAAP/////+AAAAAAAAAAAAfAAAAP///4AAAAAAAAAAAAAAAAAAAAP+A"
    "Ae/MXAAAH/////8AAAAAAAAAAAA8AAAP/////8GAAOAAAAAAAAAAAAAAA///5+4/+AAAB/////wAAAAAAAAAAAD4AHsP////"
    "///4AMAAAAAAAAAAAAAAA///8fx//8AAD/////wAAAAAAAAAAAHwAPv////////4Af/gAAAAwAADwAAAAMf/8B8///gAAf//"
    "//4AAAAAAA/AAAB8A//////////////5wAADAAB///gAfQH//n+D//+AB/////wAAAAAAP/gAAAAAf//////////////8AIA"
    "AAD////P//x//P/j4f+AAP///+AAAAAAB///AAAA/P////////////////v/4Af////////B8Hf34b+AA////gAAAAAAH///"
    "8eHf////////////////////+AH/////////////45/wA///4AAAAAAAP////c////v//////////////////8P/////////"
    "////gD/8A///wAAcAAAAf//9+v///////////////////////8/////////////+AH+4Af/4AA/8AAAB/8f+H///////////"
    "////////////Bwf/////////////x//gAf/wAAf8AAAD/8/+////////////////////////AIAf///////////H8B/wAP/w"
    "AAHgAAAH/7/////////////////////////+AAH///////////+A4AewAH/AAAAAAAA//n//////////////////////////"
    "AAP///////////4AH/BAAD/AAAAAAAD//H///////////////////////v/wAAP///////////wAA/4AAB/AAAAAAAB//H//"
    "////////////////////nf+AAA///x////////wAA/4QAAGAAAAAAAB//jj////////////////////+B/YAAAB/6AD/////"
    "//wAB/44AAAAAAAAAAB//h////////////////////meDwAAAAAD4AA///////4AA//8AAAAAAAAA4A5+B//////////////"
    "/////8AAPgAAAAADcAAD//////8AAf/+AAAAAAAAA8AH+G///////////////////wAA/wAAAAAOAAAB///////wAf/+AAAA"
    "AAAAA8AO+H///////////////////gAB/wAAAAB4AAAB///////+A///AAAAAAAAA+AP4H//////////////////+AAB/AAA"
    "AAHAAAAAf///////z///4AAAAAAAHeAMB///////////////////8AAB/AAAAAAAAAADv///////z///8AAAAAAAPHAP////"
    "/////////////////6AB+AAAAAAAAAABP///////5///+AAAAAAAPfj///////////////////////AA4AAAAAAAAAAAD///"
    "////5///+AAAAAAAO/z///////////////////////AA4AAAAAAAAAAAD///////////2AAAAAAAAf//////////////////"
    "/////7AAwAAAAAAAAAAAH//////////PMAAAAAAAA4f//////////////////////7AAAAAAAAAAAAAAB/////////+OfgAA"
    "AAAAAD///////////////////////7gAAAAAAAAAAAAAAf/////////w/gAAAAAAAf///////////////////////+AAAAAA"
    "AAAAAAAAAf/////////wDwAAAAAAAH///////////////////////2AAAAAAAAAAAAAAAf/////////5AgAAAAAAAD//////"
    "f/5//////////////nAAAAAAAAAAAAAAAP//////////AAAAAAAAAD/////nf/h//////////////AAAAAAAAAAAAAAAAP//"
    "///////8AAAAAAAAAD/////Hf+H/////////////+GAAAAAAAAAAAAAAAf////////5wAAAAAAAAAD/7n/+AH/P/////////"
    "////8HwAAAAAAAAAAAAAAf////////wAAAAAAAAAP/8Dx/8AD/H/////////////4PgAAAAAAAAAAAAAAf////////wAAAAA"
    "AAAAP/8N4/8AB/j////////////+AfAAAAAAAAAAAAAAAf////////AAAAAAAAAAH/4A+f+fz/y////////////8AMAAAAAA"
    "AAAAAAAAAf///////+AAAAAAAAAAH/gMP/v///7///////////v4AcAAAAAAAAAAAAAAAP///////8AAAAAAAAAAP/AMHPP/"
    "//x///////////ZwAMAAAAAAAAAAAAAAAP///////4AAAAAAAAAAP/AAGPP///h//////////8D4AcAAAAAAAAAAAAAAAH//"
    "/////4AAAAAAAAAAH/AA8HH///x//////////+w8A4AAAAAAAAAAAAAAAH///////4AAAAAAAAAAB8P+MHH/////////////"
    "//w8D4AAAAAAAAAAAAAAAD///////4AAAAAAAAAAAB/+AAAA//////////////g8H4AAAAAAAAAAAAAAAB///////wAAAAAA"
    "AAAAB//+AAwN//////////////A4/wAAAAAAAAAAAAAAAAf//////gAAAAAAAAAAD//+AAAB//////////////gD+AAAAAAA"
    "AAAAAAAAAAP/////+AAAAAAAAAAAH///AAAB//////////////gHwAAAAAAAAAAAAAAAAAH/////8AAAAAAAAAAAP///8PAD"
    "//////////////wDAAAAAAAAAAAAAAAAAAH/////4AAAAAAAAAAAP///8f9z//////////////wDAAAAAAAAAAAAAAAAAAH/"
    "////4AAAAAAAAAAAP/////////////////////wAAAAAAAAAAAAAAAAAAADf//zg4AAAAAAAAAAAP/////////v/////////"
    "//4AAAAAAAAAAAAAAAAAAABv//gAcAAAAAAAAAAA//////////v///////////wAAAAAAAAAAAAAAAAAAAD3/+AAcAAAAAAA"
    "AAAB//////////n///////////gAAAAAAAAAAAAAAAAAAAA//+AAdgAAAAAAAAAD///////8//x3//////////gAAAAAAAAA"
    "AAAAAAAAAAAb/+AAMgAAAAAAAAAH///////+//8f//////////AAAAAAAAAAAAAAAAAAAAAd/+AABgAAAAAAAAAH///////+"
    "f/84A/////////QAAAAAAAAAAAAAAAAAAAAM/+AAAgAAAAAAAAAP////////f//4Af///////+wAAAAAAAAAAAAAAAAAAAAG"
    "f+AAAAAAAAAAAAAf////////P//+AP///////4wAAAAAAAAAAAAAAAAAAAAAP+AB/AAAAAAAAAAf////////n///AH//////"
    "/ggAAAAAAAAAAAAGAAAAAAAAP+AcBwAAAAAAAAA/////////3///AH//4P//cAAAAAAAAAAAAAAAAAAAAAAAP+B4A8AAAAAA"
    "AAAf////////3//+AA//4P/+YAAAAAAAAAAAAAABwAAAAAAAP/B4ADwAAAAAAAAf////////z//8AA//wH/84AAAAAAAAAAA"
    "AAAAAAAAAAAAD/j4AB8AAAAAAAAf////////x//4AA//gH/84AAAAAAAAAAAAAAAAAAAAAAAA//wAwgAAAAAAAAf////////"
    "5//wAAf/AD/+AA4AAAAAAAAAAAAAAAAAAAAAAf/wAAAAAAAAAAAf////////4//gAAf+AD//AA4AAAAAAAAAAAAAAAAAAAAA"
    "AD/wAAAAAAAAAAAf////////8/+AAAf8ADf/gBwAAAAAAAAAAAAAAAAAAAAAAAH/gAAAAAAAAAA/////////+/8AAAP4AAf/"
    "gAwAAAAAAAAAAAAAAAAAAAAAAAD/gAAAAAAAAAA//////////fgAAAP4AAf/wA4AAAAAAAAAAAAAAAAAAAAAAAA/gAAAAAAA"
    "AAAf/////////8AAAAP4AAP/wA8AAAAAAAAAAAAAAAAAAAAAAAAPgAAAAAAAAAAf/////////wAAAAH4AAO/wATAAAAAAAAA"
    "AAAAAAAAAAAAAAAHgB4AAAAAAAAf/////////wcAAAHwAAM/wAfAAAAAAAAAAAAAAAAAAAAAAAADgP8fAAAAAAAH////////"
    "/38AAAHwAAMfABfAAAAAAAAAAAAAAAAAAAAAAAADwP/+AAAAAAAD//////////4AAAD4AAMGACNAAAAAAAAAAAAAAAAAAAAA"
    "AAAA////AAAAAAAD//////////4AAAD8AAOEAEDgAAAAAAAAAAAAAAAAAAAAAAAAN///gAAAAAAD//////////4AAAAcAAOA"
    "AAPgAAAAAAAAAAAAAAAAAAAAAAAAA///wAAAAAAB//////////wAAAAcAAGAAALgAAAAAAAAAAAAAAAAAAAAAAAAA///4AAA"
    "AAAAf/z///////wAAAAMAADgAMDAAAAAAAAAAAAAAAAAAAAAAAAAA////wAAAAAAP/B///////gAAAAAABzwAfAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAA////4AAAAAACABv//////AAAAAAAB7wA+AAAAAAAAAAAAAAAAAAAAAAAAAAA////4AAAAAAAAAH////"
    "//AAAAAAAA9wB8AAAAAAAAAAAAAAAAAAAAAAAAAAB////8AAAAAAAAAH/////+AAAAAAAAfwH8AAAAAAAAAAAAAAAAAAAAAA"
    "AAAAB////+AAAAAAAAAH/////4AAAAAAAAP4f+AYAAAAAAAAAAAAAAAAAAAAAAAAH////8AAAAAAAAAH/////wAAAAAAAAHg"
    "/8+YAAAAAAAAAAAAAAAAAAAAAAAAH////+AAAAAAAAAH/////gAAAAAAAAHwf9gQAAAAAAAAAAAAAAAAAAAAAAAAH/////wA"
    "AAAAAAAP/////AAAAAAAAADwf98D4AAAAAAAAAAAAAAAAAAAAAAAH/////8AAAAAAAAH/////AAAAAAAAAD4P5wA7gAAAAAA"
    "AAAAAAAAAAAAAAAAD//////gAAAAAAAH////+AAAAAAAAAB8P74M/8AwAAAAAAAAAAAAAAAAAAAAH//////8AAAAAAAD////"
    "8AAAAAAAAAA8A54i//gIAAAAAAAAAAAAAAAAAAAAP//////+AAAAAAAB////8AAAAAAAAAAcAB8AD/wYAAAAAAAAAAAAAAAA"
    "AAAAH///////gAAAAAAA////4AAAAAAAAAAMABoAI/7zAAAAAAAAAAAAAAAAAAAAH///////wAAAAAAA////4AAAAAAAAAAH"
    "gAAAI/8BAAAAAAAAAAAAAAAAAAAAD///////wAAAAAAA////8AAAAAAAAAAD+AAAA/8AYAAAAAAAAAAAAAAAAAAAD///////"
    "wAAAAAAAf///8AAAAAAAAAAAH2oAB/OAEAAAAAAAAAAAAAAAAAAAB///////gAAAAAAA////8AAAAAAAAAAAAADAAHPADAAA"
    "AAAAAAAAAAAAAAAAB///////AAAAAAAAf///8AAAAAAAAAAAABmAAAHgAAAAAAAAAAAAAAAAAAAAA///////AAAAAAAAf///"
    "+AAAAAAAAAAAAAAAACAAAAAAAAAAAAAAAAAAAAAAA//////+AAAAAAAAf///+AAAAAAAAAAAAAAAwHAAAAAAAAAAAAAAAAAA"
    "AAAAAf/////8AAAAAAAAf///+AwAAAAAAAAAAAAD+HAAAAAAAAAAAAAAAAAAAAAAAf/////8AAAAAAAA////+A4AAAAAAAAA"
    "AAAH+HAAAAAAAAAAAAAAAAAAAAAAAf/////8AAAAAAAA////+B4AAAAAAAAAAAB/8HgAAAAAAAAAAAAAAAAAAAAAAH/////8"
    "AAAAAAAB////+D4AAAAAAAAAAAD/+HwAADAAgAAAAAAAAAAAAAAAAD/////4AAAAAAAB////8PwAAAAAAAAAAAH//HwAABAB"
    "AAAAAAAAAAAAAAAAAA/////4AAAAAAAB////4PwAAAAAAAAAAAP///wAAAAAAAAAAAAAAAAAAAAAAAf////4AAAAAAAB////"
    "gPwAAAAAAAAAAAP///4AAAAGAAAAAAAAAAAAAAAAAAf////4AAAAAAAA////APwAAAAAAAAAAAf///4AAAAAAAAAAAAAAAAA"
    "AAAAAAf////wAAAAAAAA///+APgAAAAAAAAAAB////+AAAAAAAAAAAAAAAAAAAAAAAf////wAAAAAAAAf//+AfgAAAAAAAAA"
    "AP////+AAMAAAAAAAAAAAAAAAAAAAAf////wAAAAAAAAf///AfgAAAAAAAAAA//////AAGAAAAAAAAAAAAAAAAAAAAf////g"
    "AAAAAAAAP///AfAAAAAAAAAAB//////gAAAAAAAAAAAAAAAAAAAAAAf///8AAAAAAAAAP///AfAAAAAAAAAAB//////wAAAA"
    "AAAAAAAAAAAAAAAAAAf///gAAAAAAAAAP///AfAAAAAAAAAAB//////4AAAAAAAAAAAAAAAAAAAAAAf///AAAAAAAAAAP//8"
    "AMAAAAAAAAAAB//////4AAAAAAAAAAAAAAAAAAAAAAf///AAAAAAAAAAH//4AAAAAAAAAAAAB//////8AAAAAAAAAAAAAAAA"
    "AAAAAAf///AAAAAAAAAAH//4AAAAAAAAAAAAB//////8AAAAAAAAAAAAAAAAAAAAAA////AAAAAAAAAAH//4AAAAAAAAAAAA"
    "A//////8AAAAAAAAAAAAAAAAAAAAAA///+AAAAAAAAAAD//wAAAAAAAAAAAAA//////8AAAAAAAAAAAAAAAAAAAAAA///+AA"
    "AAAAAAAAB//gAAAAAAAAAAAAAf/////8AAAAAAAAAAAAAAAAAAAAAA///8AAAAAAAAAAB//gAAAAAAAAAAAAAf/////8AAAA"
    "AAAAAAAAAAAAAAAAAA///4AAAAAAAAAAA//AAAAAAAAAAAAAAf/9///4AAAAAAAAAAAAAAAAAAAAAA///wAAAAAAAAAAA/+A"
    "AAAAAAAAAAAAAf/AP//4AAAAAAAAAAAAAAAAAAAAAA///gAAAAAAAAAAA/4AAAAAAAAAAAAAAf+AP//wAAAAAAAAAAAAAAAA"
    "AAAAAB///gAAAAAAAAAAA8AAAAAAAAAAAAAAAfAAH//gAAAAAAAAAAAAAAAAAAAAAB//4AAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAC//gAABgAAAAAAAAAAAAAAAAAB//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/gAABgAAAAAAAAAAAAAAAAAD//8AAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/AAAAwAAAAAAAAAAAAAAAAAD//4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAA+"
    "AAAAAAAAAAAAAAAAAD//AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYAAAA+AAAAAAAAAAAAAAAAAD/8AAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAAD/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAACYAAAAAAAAAAAA"
    "AAAAAD/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+AAAHwAAAAAAAAAAAAAAAAAH/4AAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAeAAAHAAAAAAAAAAAAAAAAAAD/wAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAOAAAAAAAAAAAAAAAAAAH/gAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8AAAAAAAAAAAAAAAAAAH/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB8A"
    "AAAAAAAAAAAAAAAAAP+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD4AAAAAAAAAAAAAAAAAAH/AAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAP+AAAAAAAAAAAAAAAAAAAAAAMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+AAAAAAAAAAAAAAAAAAAAAAOAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP8B4AAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAH4AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAH8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAB+AAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
    "AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA"
)

_LAND_THRESHOLD = 0.30


@lru_cache(maxsize=1)
def bitmap() -> list[list[bool]]:
    """The decoded land bitmap as HEIGHT rows of WIDTH booleans."""
    raw = base64.b64decode(_BITMAP_B64)
    return [
        [
            bool((raw[(row * WIDTH + col) // 8] >> (7 - (row * WIDTH + col) % 8)) & 1)
            for col in range(WIDTH)
        ]
        for row in range(HEIGHT)
    ]


@lru_cache(maxsize=1)
def _integral() -> list[list[int]]:
    """Summed-area table of the land bitmap for fast box sampling."""
    raw = base64.b64decode(_BITMAP_B64)
    table = [[0] * (WIDTH + 1) for _ in range(HEIGHT + 1)]
    for row in range(HEIGHT):
        row_sum = 0
        for col in range(WIDTH):
            index = row * WIDTH + col
            bit = (raw[index // 8] >> (7 - index % 8)) & 1
            row_sum += bit
            table[row + 1][col + 1] = table[row][col + 1] + row_sum
    return table


def _land_fraction(x0: int, x1: int, y0: int, y1: int) -> float:
    table = _integral()
    x0, y0 = max(x0, 0), max(y0, 0)
    x1, y1 = min(x1, WIDTH), min(y1, HEIGHT)
    if x1 <= x0 or y1 <= y0:
        return 0.0
    covered = table[y1][x1] - table[y0][x1] - table[y1][x0] + table[y0][x0]
    return covered / ((x1 - x0) * (y1 - y0))


def sample(dots_w: int, dots_h: int) -> list[list[bool]]:
    """Resample the bitmap to an arbitrary dot grid (area threshold)."""
    grid = []
    for dot_y in range(dots_h):
        y0 = dot_y * HEIGHT // dots_h
        y1 = max((dot_y + 1) * HEIGHT // dots_h, y0 + 1)
        row = []
        for dot_x in range(dots_w):
            x0 = dot_x * WIDTH // dots_w
            x1 = max((dot_x + 1) * WIDTH // dots_w, x0 + 1)
            row.append(_land_fraction(x0, x1, y0, y1) >= _LAND_THRESHOLD)
        grid.append(row)
    return grid
